name: EXPENSES_APP
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assests/fonts/Quicksand-Regular.ttf
        - asset: assests/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: OpensSans
      fonts:
        - asset: assests/fonts/OpenSans-Regular.ttf
        - asset: assests/fonts/OpenSans-Bold.ttf
          weight: 700
  uses-material-design: true
  assets:
   - assests/images/waiting.png